# © 2020 ETH Zurich, Mechanics and Materials Lab
# © 2020 California Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

stages:
    - image-dev
    - image-docu
    - analyze
    - build
    - publish

.build-image: &build-image
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint:
            - ""
    script:
        - mkdir -p /kaniko/.docker
        - >
            printf \
                '{"auths": {"%s": {"username": "%s", "password": "%s"}}}' \
                "$CI_REGISTRY" \
                "$CI_REGISTRY_USER" \
                "$CI_REGISTRY_PASSWORD" > /kaniko/.docker/config.json
        - >
            /kaniko/executor \
                --build-arg PETSC_SCALAR_TYPE=$PETSC_SCALAR_TYPE \
                --cache-ttl=730h \
                --cache=true \
                --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG \
                --dockerfile docker/$DOCKERFILE_NAME

build-image-dev-real:
    stage: image-dev
    variables:
        DOCKERFILE_NAME: "Dockerfile"
        PETSC_SCALAR_TYPE: "real"
        IMAGE_NAME: "dev-real"
    <<: *build-image

build-image-dev-complex:
    stage: image-dev
    variables:
        DOCKERFILE_NAME: "Dockerfile"
        PETSC_SCALAR_TYPE: "complex"
        IMAGE_NAME: "dev-complex"
    <<: *build-image

build-image-docu:
    stage: image-docu
    variables:
        DOCKERFILE_NAME: "Dockerfile_docu"
        IMAGE_NAME: "docu"
    <<: *build-image

check-code-format:
    stage: analyze
    needs: ["build-image-dev-real"]
    image: $CI_REGISTRY_IMAGE/dev-real:$CI_COMMIT_REF_SLUG
    script:
        - >
            find . \
                -name "*.h" -print0 \
                -o \
                -name "*.cc" -print0 | \
            xargs -0 -I {} -P $(nproc) \
                bash -c 'diff <(cat {}) <(clang-format {})'

check-license-header:
    stage: analyze
    needs: ["build-image-dev-real"]
    image: $CI_REGISTRY_IMAGE/dev-real:$CI_COMMIT_REF_SLUG
    script:
        - >
            grep \
                --recursive \
                --exclude-dir='.git' \
                --exclude='*.json' \
                --exclude='*.txt' \
                --exclude='*.vtu' \
                --files-without-match "Apache License" \
                .

check-script:
    stage: analyze
    needs: ["build-image-dev-real"]
    image: $CI_REGISTRY_IMAGE/dev-real:$CI_COMMIT_REF_SLUG
    script:
        - find . -name "*.py" -print0 | xargs -0 python3 -m black --check
        - find . -name "*.py" -print0 | xargs -0 python3 -m pylint --generated-members=vtk.*
        - find . -name "*.py" -print0 | xargs -0 python3 -m mypy --python-version 3.7 --ignore-missing
        - find . -name "*.py" -print0 | xargs -0 python3 -m doctest

.build-library: &build-library
    stage: build
    coverage: '/^lines:\s*\d+\.\d+\%/'
    script:
        - useradd developer
        - mkdir build
        - chown developer:developer build
        - >
            su developer -c '
                cd build
                cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage -Werror -Wall -Wextra -Wpedantic" .. &&
                cmake --build . &&
                GTEST_OUTPUT="xml:gtest-results.xml" ctest --output-on-failure --exclude-regex ".*_mpi$" &&
                ctest --output-on-failure --tests-regex ".*_mpi$" &&
                python3 -m gcovr --print-summary --xml coverage.xml -j$(nproc) --root .. .
            '
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: build/coverage.xml
            junit: build/*/test/gtest-results.xml
        when: always

build-library-real:
    image: $CI_REGISTRY_IMAGE/dev-real:$CI_COMMIT_REF_SLUG
    needs: ["build-image-dev-real"]
    <<: *build-library

build-library-complex:
    image: $CI_REGISTRY_IMAGE/dev-complex:$CI_COMMIT_REF_SLUG
    needs: ["build-image-dev-complex"]
    <<: *build-library

.install-library: &install-library
    stage: build
    script:
        - mkdir build
        - >
            bash -c '
                cd build &&
                cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug .. &&
                cmake --build . --target install
            '
        - mkdir build-examples
        - >
            bash -c '
                cd build-examples &&
                cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../examples &&
                cmake --build .
            '

install-library-real:
    image: $CI_REGISTRY_IMAGE/dev-real:$CI_COMMIT_REF_SLUG
    needs: ["build-image-dev-real"]
    <<: *install-library

install-library-complex:
    image: $CI_REGISTRY_IMAGE/dev-complex:$CI_COMMIT_REF_SLUG
    needs: ["build-image-dev-complex"]
    <<: *install-library

build-documentation:
    stage: build
    needs: ["build-image-docu"]
    image: $CI_REGISTRY_IMAGE/docu:$CI_COMMIT_REF_SLUG
    script:
        - mkdir build
        - >
            bash -c '
                cd build &&
                ../docs/build_documentation
            '
    artifacts:
        paths:
            - build/build/
        expose_as: manual

build-euler-modules:
    stage: build
    needs: []
    script:
        - . requirements/euler.sh
        - cmake -S . -B build-release -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_TOOLCHAIN_FILE=/cluster/project/mandm/libraries/EulerToolchain.cmake
        - bsub -Ip -n 32 -W00:10 'cmake --build build-release --target all'
        - bsub -Ip -n 3 -W00:10 'cmake --build build-release --target test'
    tags:
        - euler
    only:
        - main

prepare-html:
    stage: build
    needs: ["build-documentation"]
    script:
        - mkdir public
        - cp -r build/build/html public
    artifacts:
        paths:
            - public/

publish-html:
    stage: publish
    image: alpine
    before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$PUBLISH_KEY" | tr -d '\r' | ssh-add - > /dev/null 2>/dev/null
        - host="${PUBLISH_URL%:*}"
        - host="${host#*@}"
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan "$host" 2>/dev/null >> ~/.ssh/known_hosts
        - >
            [ -n "$CI_COMMIT_BRANCH" ] \
              && [ "$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH" ] \
              && mv public "${CI_COMMIT_BRANCH}" \
              && mkdir public && mv "${CI_COMMIT_BRANCH}" public/
    script:
        - |-
          sftp -q -b - "${PUBLISH_URL%:*}" <<EOF
          put -r public/* ${PUBLISH_URL#*:}
          EOF
    rules:
        - if: '$CI_COMMIT_REF_PROTECTED && $PUBLISH_URL && $PUBLISH_KEY'
