# © 2021 ETH Zurich, Mechanics and Materials Lab
#
# This file is part of ae108.
#
# ae108 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or any
# later version.
#
# ae108 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ae108. If not, see <https://www.gnu.org/licenses/>.

version: "3.3"
services:
  dev-real:
    build:
      args:
        PETSC_SCALAR_TYPE: real
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/mnt/io
    tty: true
    shm_size: '1gb'
    working_dir: /mnt/io
  dev-complex:
    build:
      args:
        PETSC_SCALAR_TYPE: complex
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/mnt/io
    working_dir: /mnt/io
    tty: true
    shm_size: '1gb'
  dev-doc:
    build:
      context: ./docker
      dockerfile: Dockerfile_docu
    volumes:
      - .:/mnt/io
    working_dir: /mnt/io
    tty: true
