#!/bin/bash

# © 2020 ETH Zurich, Mechanics and Materials Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
ROOT_DIRECTORY=$(readlink -e $(dirname "$0"))/..

(
    doxygen -g -; \
    echo GENERATE_HTML=NO; \
    echo GENERATE_LATEX=NO; \
    echo GENERATE_XML=YES; \
    echo INPUT="$ROOT_DIRECTORY/elements/src/include" \
               "$ROOT_DIRECTORY/cmdline/src/include" \
               "$ROOT_DIRECTORY/cpppetsc/src/include" \
               "$ROOT_DIRECTORY/assembly/src/include" \
               "$ROOT_DIRECTORY/solve/src/include" \
               "$ROOT_DIRECTORY/examples"; \
    echo RECURSIVE=YES; \
    echo PROJECT_NAME=\"ae108\" \
) \
| doxygen -

sphinx-quickstart \
    --no-batchfile \
    --sep \
    -a "Mechanics & Materials Lab, ETH Zurich" \
    -l "en" \
    -p "ae108" \
    -r "$(git describe)"

cat <<EOF >> source/conf.py
#

root_doc = 'index'
extensions = [ "breathe", "sphinx_design"]
breathe_projects = { "ae108": "$PWD/xml" }
breathe_default_project = "ae108"
html_context = {"default_mode": "dark"}
html_static_path = ['_static']
html_theme = "pydata_sphinx_theme"
html_favicon = "_static/favicon.ico"
html_theme_options = {
    "logo": {
        "image_light": "logo_light.svg",
        "image_dark": "logo_dark.svg",
    },
    "icon_links": [
        {
            "name": "GitLab",
            "url": "https://gitlab.ethz.ch/mechanics-and-materials/ae108",
            "icon": "fa-brands fa-gitlab",
        },
        {
            "name": "Mechanics & Materials Lab",
            "url": "https://mm.ethz.ch/",
            "icon": "fa-solid fa-flask",
        },
        {
            "name": "Twitter",
            "url": "https://twitter.com/DennisKochmann",
            "icon": "fa-brands fa-twitter",
        },
    ],
}
html_title = "ae108"
html_show_sourcelink = False
EOF

cp -rs "$ROOT_DIRECTORY/docs/_static/" source/

ln -sf "$ROOT_DIRECTORY/docs/index.rst" source/index.rst

ln -sf "$ROOT_DIRECTORY/docs/quickstart.rst" source/quickstart.rst
ln -sf "$ROOT_DIRECTORY/docs/libraries.rst" source/libraries.rst
ln -sf "$ROOT_DIRECTORY/docs/faq.rst" source/faq.rst

ln -s "$ROOT_DIRECTORY/elements" source/elements
ln -s "$ROOT_DIRECTORY/cmdline" source/cmdline
ln -s "$ROOT_DIRECTORY/examples" source/examples

make -j$(nproc) html
make -j$(nproc) latexpdf