#!/bin/bash

# © 2020 ETH Zurich, Mechanics and Materials Lab
#
# This file is part of ae108.
#
# ae108 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or any
# later version.
#
# ae108 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ae108. If not, see <https://www.gnu.org/licenses/>.

set -e
ROOT_DIRECTORY=$(readlink -e $(dirname "$0"))/..

(
    doxygen -g -; \
    echo GENERATE_HTML=NO; \
    echo GENERATE_LATEX=NO; \
    echo GENERATE_XML=YES; \
    echo INPUT="$ROOT_DIRECTORY/elements/src/include" \
               "$ROOT_DIRECTORY/cmdline/src/include" \
               "$ROOT_DIRECTORY/cpppetsc/src/include" \
               "$ROOT_DIRECTORY/assembly/src/include" \
               "$ROOT_DIRECTORY/solve/src/include" \
               "$ROOT_DIRECTORY/examples"; \
    echo RECURSIVE=YES; \
    echo PROJECT_NAME=\"ae108\" \
) \
| doxygen -

sphinx-quickstart \
    --no-batchfile \
    --sep \
    -a "Mechanics & Materials Lab, ETH Zurich" \
    -l "en" \
    -p "ae108" \
    -r "$(git describe)"

cat <<EOF >> source/conf.py
#

root_doc = 'index'
extensions = [ "breathe", "sphinx_design"]
breathe_projects = { "ae108": "$PWD/xml" }
breathe_default_project = "ae108"
html_context = {"default_mode": "dark"}
html_static_path = ['_static']
html_theme = "pydata_sphinx_theme"
html_favicon = "_static/favicon.ico"
html_theme_options = {
    "logo": {
        "image_light": "logo_light.svg",
        "image_dark": "logo_dark.svg",
    },
    "icon_links": [
        {
            "name": "GitLab",
            "url": "https://gitlab.ethz.ch/mechanics-and-materials/ae108",
            "icon": "fa-brands fa-gitlab",
        },
        {
            "name": "Mechanics & Materials Lab",
            "url": "https://mm.ethz.ch/",
            "icon": "fa-solid fa-flask",
        },
        {
            "name": "Twitter",
            "url": "https://twitter.com/DennisKochmann",
            "icon": "fa-brands fa-twitter",
        },
    ],
}
html_title = "ae108"
html_show_sourcelink = False
EOF

cp -rs "$ROOT_DIRECTORY/docs/_static/" source/

ln -sf "$ROOT_DIRECTORY/docs/index.rst" source/index.rst

ln -sf "$ROOT_DIRECTORY/docs/quickstart.rst" source/quickstart.rst
ln -sf "$ROOT_DIRECTORY/docs/libraries.rst" source/libraries.rst
ln -sf "$ROOT_DIRECTORY/docs/faq.rst" source/faq.rst

ln -s "$ROOT_DIRECTORY/elements" source/elements
ln -s "$ROOT_DIRECTORY/cmdline" source/cmdline
ln -s "$ROOT_DIRECTORY/examples" source/examples

make -j$(nproc) html
sed -i -e "s/🐧/Linux/g" -e "s/🪟/Windows/g" -e "s/🍏/Mac/g" source/index.rst
make -j$(nproc) latexpdf
